version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.js
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync
    environment:
      - mongodb+srv://university-admin:As9YqEiswwEnn3Bt@cluster0.pe8bb.mongodb.net/?retryWrites=true&w=majority

        # define the local db service
    # db:
    #   image: mongo:latest
    #   ports:
    #     - 27017:27017
    #   volumes:
    #     - tasked:/data/db

volumes:
  tasked:
